[logging]
level = "debug"
output = "stdout"
format = "text"

[api]
enabled = true  # true | false
bind = ":1888"  # bind host:port

[servers.sin]
bind = "0.0.0.0:1443"
protocol = "tcp"
balance = "weight"

  [servers.sin.discovery]
  interval = "600s"
  kind = "plaintext"
  plaintext_endpoint = "https://mirror.ghproxy.com/raw.githubusercontent.com/getdo/bestip-config/main/SIN.txt"

  [servers.sin.healthcheck]
  kind = "exec"
  interval = "600s"
  timeout = "5s"
  exec_command = "/usr/share/cf_ip_healthcheck.sh"
  exec_expected_positive_output = "1"
  exec_expected_negative_output = "0"
  
[servers.hkg]
bind = "0.0.0.0:2443"
protocol = "tcp"
balance = "weight"

  [servers.hkg.discovery]
  interval = "600s"
  kind = "plaintext"
  plaintext_endpoint = "https://mirror.ghproxy.com/raw.githubusercontent.com/getdo/bestip-config/main/HKG.txt"

  [servers.hkg.healthcheck]
  kind = "exec"
  interval = "600s"
  timeout = "5s"
  exec_command = "/usr/share/cf_ip_healthcheck.sh"
  exec_expected_positive_output = "1"
  exec_expected_negative_output = "0"

[servers.nrt]
bind = "0.0.0.0:3443"
protocol = "tcp"
balance = "weight"

  [servers.nrt.discovery]
  interval = "600s"
  kind = "plaintext"
  plaintext_endpoint = "https://mirror.ghproxy.com/raw.githubusercontent.com/getdo/bestip-config/main/NRT.txt"

  [servers.nrt.healthcheck]
  kind = "exec"
  interval = "600s"
  timeout = "5s"
  exec_command = "/usr/share/cf_ip_healthcheck.sh"
  exec_expected_positive_output = "1"
  exec_expected_negative_output = "0"
