[logging]
level = "debug"
output = "stdout"
format = "text"

[servers.sin]
bind = "0.0.0.0:1443"
protocol = "tcp"
balance = "weight"

  [servers.sin.discovery]
  interval = "600s"
  kind = "plaintext"
  plaintext_endpoint = "https://ghproxy.com/raw.githubusercontent.com/getdo/bestip-config/main/SIN.txt"

  [servers.sin.healthcheck]
  kind = "ping"
  interval = "60s"
  ping_timeout_duration = "500ms"
  
[servers.hkg]
bind = "0.0.0.0:2443"
protocol = "tcp"
balance = "weight"

  [servers.hkg.discovery]
  interval = "600s"
  kind = "plaintext"
  plaintext_endpoint = "https://ghproxy.com/raw.githubusercontent.com/getdo/bestip-config/main/HKG.txt"

  [servers.hkg.healthcheck]
  kind = "ping"
  interval = "60s"
  ping_timeout_duration = "500ms"
