[logging]
level = "debug"
output = "stdout"
format = "text"

[servers.sin]
bind = "0.0.0.0:1443"
protocol = "tcp"
balance = "iphash"

[servers.hkg]
bind = "0.0.0.0:2443"
protocol = "tcp"
balance = "iphash"

[servers.sin.discovery]
interval = "60s"
kind = "plaintext"
plaintext_endpoint = "https://ghproxy.com/https://raw.githubusercontent.com/getdo/bestip-config/main/SIN.txt"

[servers.hkg.discovery]
interval = "60s"
kind = "plaintext"
plaintext_endpoint = "https://ghproxy.com/https://raw.githubusercontent.com/getdo/bestip-config/main/HKG.txt"
